server:
  port: 8087

spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-hystrix-demo
eureka:
  instance:
    hostname: demo
    prefer-ip-address: true
    instance-id: localhost:8087
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/,http://localhost:5070/eureka/
    eureka-server-read-timeout-seconds: 4

#  feign日志
logging:
  level:
    org.example.service.UserService: debug
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000