server:
  port: 8087


spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-client-demo

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.txt
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.model
  config-location: classpath:mybatis-config.xml
#  feign日志
logging:
  level:
    org.example.service.UserService: debug
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
  endpoint:
    health:
      show-details: always

ignore:
  urls:
    - /
    - /error
    - /favicon.ico
    - /**/*swagger*/**
    - /v2/api-docs
    - /csrf
    - /actuator/**
    - /hystrix.sender
    - /v1/sms/**
    - /v1/user/anonymousUser/**
    - /v1/tenant/anonymousUser/**
    - /v1/menu/anonymousUser/**
    - /v1/examination/anonymousUser/**
    - /v1/answer/anonymousUser/**
    - /v1/examRecord/anonymousUser/**
    - /v1/examRecord/currentTime
    - /v1/subject/anonymousUser/**
    - /v1/answer/anonymousUser/**
    - /v1/code/**
    - /v1/attachment/download
    - /v1/log/**
    - /authentication/**
    - /v1/authentication/**
    - /**/*.css
    - /**/*.js
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**