server:
  port: 8087


spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-client-demo
eureka:
  instance:
    hostname: demo
    prefer-ip-address: true
    instance-id: localhost:8087
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/,http://localhost:5070/eureka/

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.model
  config-location: classpath:mybatis-config.xml