server:
  port: 5070
eureka:
  instance:
    hostname: localhost2
  client:
    ## 不注册自己
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:5060/eureka/
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false